#!/bin/bash

set -e

rm data/iccma15_testcases/rdm1000_0.apx
rm data/iccma15_testcases/rdm1000_1.apx
rm data/iccma15_testcases/rdm1000_2.apx
rm data/iccma15_testcases/rdm1000_3.apx
rm data/iccma15_testcases/rdm1000_4.apx
rm data/iccma15_testcases/rdm1000_5.apx

rm data/iccma15_solutions/real_0.EE-CO
rm data/iccma15_solutions/real_0.EE-GR
rm data/iccma15_solutions/real_0.EE-PR
rm data/iccma15_solutions/real_0.EE-ST
rm data/iccma15_solutions/real_1.EE-CO
rm data/iccma15_solutions/real_1.EE-GR
rm data/iccma15_solutions/real_1.EE-PR
rm data/iccma15_solutions/real_1.EE-ST
rm data/iccma15_solutions/real_10.EE-CO
rm data/iccma15_solutions/real_10.EE-GR
rm data/iccma15_solutions/real_10.EE-PR
rm data/iccma15_solutions/real_10.EE-ST
rm data/iccma15_solutions/real_11.EE-CO
rm data/iccma15_solutions/real_11.EE-GR
rm data/iccma15_solutions/real_11.EE-PR
rm data/iccma15_solutions/real_11.EE-ST
rm data/iccma15_solutions/real_12.EE-CO
rm data/iccma15_solutions/real_12.EE-GR
rm data/iccma15_solutions/real_12.EE-PR
rm data/iccma15_solutions/real_12.EE-ST
rm data/iccma15_solutions/real_13.EE-CO
rm data/iccma15_solutions/real_13.EE-GR
rm data/iccma15_solutions/real_13.EE-PR
rm data/iccma15_solutions/real_13.EE-ST
rm data/iccma15_solutions/real_14.EE-CO
rm data/iccma15_solutions/real_14.EE-GR
rm data/iccma15_solutions/real_14.EE-PR
rm data/iccma15_solutions/real_14.EE-ST
rm data/iccma15_solutions/real_15.EE-CO
rm data/iccma15_solutions/real_15.EE-GR
rm data/iccma15_solutions/real_15.EE-PR
rm data/iccma15_solutions/real_15.EE-ST
rm data/iccma15_solutions/real_16.EE-CO
rm data/iccma15_solutions/real_16.EE-GR
rm data/iccma15_solutions/real_16.EE-PR
rm data/iccma15_solutions/real_16.EE-ST
rm data/iccma15_solutions/real_17.EE-CO
rm data/iccma15_solutions/real_17.EE-GR
rm data/iccma15_solutions/real_17.EE-PR
rm data/iccma15_solutions/real_17.EE-ST
rm data/iccma15_solutions/real_18.EE-CO
rm data/iccma15_solutions/real_18.EE-GR
rm data/iccma15_solutions/real_18.EE-PR
rm data/iccma15_solutions/real_18.EE-ST
rm data/iccma15_solutions/real_19.EE-CO
rm data/iccma15_solutions/real_19.EE-GR
rm data/iccma15_solutions/real_19.EE-PR
rm data/iccma15_solutions/real_19.EE-ST
rm data/iccma15_solutions/real_2.EE-CO
rm data/iccma15_solutions/real_2.EE-GR
rm data/iccma15_solutions/real_2.EE-PR
rm data/iccma15_solutions/real_2.EE-ST
rm data/iccma15_solutions/real_3.EE-CO
rm data/iccma15_solutions/real_3.EE-GR
rm data/iccma15_solutions/real_3.EE-PR
rm data/iccma15_solutions/real_3.EE-ST
rm data/iccma15_solutions/real_4.EE-CO
rm data/iccma15_solutions/real_4.EE-GR
rm data/iccma15_solutions/real_4.EE-PR
rm data/iccma15_solutions/real_4.EE-ST
rm data/iccma15_solutions/real_5.EE-CO
rm data/iccma15_solutions/real_5.EE-GR
rm data/iccma15_solutions/real_5.EE-PR
rm data/iccma15_solutions/real_5.EE-ST
rm data/iccma15_solutions/real_6.EE-CO
rm data/iccma15_solutions/real_6.EE-GR
rm data/iccma15_solutions/real_6.EE-PR
rm data/iccma15_solutions/real_6.EE-ST
rm data/iccma15_solutions/real_7.EE-CO
rm data/iccma15_solutions/real_7.EE-GR
rm data/iccma15_solutions/real_7.EE-PR
rm data/iccma15_solutions/real_7.EE-ST
rm data/iccma15_solutions/real_8.EE-CO
rm data/iccma15_solutions/real_8.EE-GR
rm data/iccma15_solutions/real_8.EE-PR
rm data/iccma15_solutions/real_8.EE-ST
rm data/iccma15_solutions/real_9.EE-CO
rm data/iccma15_solutions/real_9.EE-GR
rm data/iccma15_solutions/real_9.EE-PR
rm data/iccma15_solutions/real_9.EE-ST
