standard:
  script:
    - autoconf
    - CXXFLAGS="-O3 -march=core2 -mtune=generic -pipe -fomit-frame-pointer" ./configure --without-gist
    - ./scripts/generate-make-mk.sh
    - make
    - ./bin/asgl
    - ASGL_HOME=`pwd` ./bin/asgl --check tests/tests-quick.lisp
    - make data/iccma15_solutions data/iccma15_testcases
    - cucumber --tags ~@slow
    - cucumber --tags @slow
    - xz -k bin/asgl
    - du -h bin/*
    - s3put bin/asgl.xz bin/$(git describe)/without-gist/asgl.xz

enable-timing:
  script:
    - autoconf
    - CXXFLAGS="-O3 -march=core2 -mtune=generic -pipe -fomit-frame-pointer" ./configure --without-gist --enable-timing
    - ./scripts/generate-make-mk.sh
    - make
    - ./bin/asgl
    - xz -k bin/asgl
    - du -h bin/*
    - s3put bin/asgl.xz bin/$(git describe)/without-gist_enable-timing/asgl.xz

enable-fobj-leak-checks:
  script:
    - autoconf
    - CXXFLAGS="-O3 -march=core2 -mtune=generic -pipe -fomit-frame-pointer" ./configure --without-gist --enable-fobj-leak-checks
    - ./scripts/generate-make-mk.sh
    - make
    - ./bin/asgl
    - ASGL_HOME=`pwd` ./bin/asgl --check tests/tests-quick.lisp
    - xz -k bin/asgl
    - du -h bin/*
    - s3put bin/asgl.xz bin/$(git describe)/without-gist_fobj-leak-checks/asgl.xz
