normal-full:
  script:
    - ./gitlab-ci/run.sh full

normal-light:
  script:
    - ./gitlab-ci/run.sh light

cover:
  script:
    - ./gitlab-ci/run.sh light --enable-cover

timing:
  script:
    - ./gitlab-ci/run.sh none --enable-timing

logging:
  script:
    - ./gitlab-ci/run.sh light --enable-logging

fobj-leak-checks:
  script:
    - ./gitlab-ci/run.sh light --enable-fobj-leak-checks
