job1:
  script:
    - autoconf
    - ./configure --without-gist
    - ./scripts/generate-make-mk.sh
    - make
    - ./bin/asgl
    - make data/iccma15_solutions data/iccma15_testcases
    - cucumber --tags ~@slow
    - cucumber --tags @slow
    - xz -k bin/asgl
    - du -h bin/*
    - s3put bin/asgl.xz bin/$(git describe)/without-gist/asgl.xz

job2:
  script:
    - autoconf
    - ./configure --without-gist --enable-timing
    - ./scripts/generate-make-mk.sh
    - make
    - ./bin/asgl
    - xz -k bin/asgl
    - du -h bin/*
    - s3put bin/asgl.xz bin/$(git describe)/without-gist_enable-timing/asgl.xz
