language: lisp

env:
  matrix:
    #- LISP=abcl
    #- LISP=allegro
    #- LISP=sbcl
    #- LISP=sbcl32
    #- LISP=ccl
    #- LISP=ccl32
    #- LISP=clisp
    #- LISP=clisp32
    #- LISP=cmucl
    - LISP=ecl

# matrix:
#   allow_failures:
#     - env: LISP=ccl32

install:
  - g++ --version
  - as --version
  - ld --version
  - curl --no-progress-bar --retry 10 -o "ecl.tar.gz" -L "http://178.62.230.106/packages/ecl-13.5.1-amd64.tgz"
  - md5sum ecl.tar.gz
  - sudo tar -C / -xzf "ecl.tar.gz"
  - bundle install
  #- curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh
  #- if [ "${LISP:(-2)}" = "32" ]; then
  #    sudo apt-get install libc6-dev-i386 libffi-dev:i386;
  #  fi
  #- mkdir -p ~/quicklisp/dists/pauldist
  #- curl -L http://pauldist.kisp.in/pauldist.txt > ~/quicklisp/dists/pauldist/distinfo.txt
  #- touch  ~/quicklisp/dists/pauldist/enabled.txt
  #- git clone --depth=1 git://github.com/trivial-features/trivial-features.git ~/lisp/trivial-features
  #- git clone git://common-lisp.net/projects/alexandria/alexandria.git ~/lisp/alexandria
  #- git clone --depth=1 git://github.com/cl-babel/babel.git ~/lisp/babel

script:
  - bundle exec cucumber
  - ecl -norc -eval '(format t "~A ~A~%~S~%" (lisp-implementation-type) (lisp-implementation-version) *features*)' -eval '(quit)'
  #- cl -e '(ql:quickload "graph-tgf-test")
  #         (uiop:quit (if (myam:load-and-run! "graph-tgf-test") 0 1))'
