language: lisp

env:
  matrix:
    - VARIANT=ref
    - VARIANT=v1
    - VARIANT=gr1

install:
  - sudo apt-get update
  - sudo apt-get install libgmp-dev
  - sudo apt-get install libmpfr-dev
  - sudo apt-get install libffi-dev
  #- sudo apt-get install flex
  #- sudo apt-get install bison
  #- sudo apt-get install libqt4-dev

  - g++ --version
  - as --version
  - ld --version
  - ragel --version

  - curl --no-progress-bar --retry 10 -o "gecode.tar.bz2" -L "http://178.62.230.106/packages/gecode-4.3.3-complete-amd64.tar.bz2"
  - md5sum gecode.tar.bz2
  - sudo tar -C / -xjf "gecode.tar.bz2"
  - rm gecode.tar.bz2

  - curl --no-progress-bar --retry 10 -o "ecl.tar.gz" -L "http://178.62.230.106/packages/ecl-13.5.1-amd64.tgz"
  - md5sum ecl.tar.gz
  - sudo tar -C / -xzf "ecl.tar.gz"
  - rm ecl.tar.gz

  - sudo ldconfig

  - bundle install

  - bash scripts/generate-make-mk.sh

  - make install-$VARIANT
  #- curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh
  #- if [ "${LISP:(-2)}" = "32" ]; then
  #    sudo apt-get install libc6-dev-i386 libffi-dev:i386;
  #  fi
  #- mkdir -p ~/quicklisp/dists/pauldist
  #- curl -L http://pauldist.kisp.in/pauldist.txt > ~/quicklisp/dists/pauldist/distinfo.txt
  #- touch  ~/quicklisp/dists/pauldist/enabled.txt
  #- git clone --depth=1 git://github.com/trivial-features/trivial-features.git ~/lisp/trivial-features
  #- git clone git://common-lisp.net/projects/alexandria/alexandria.git ~/lisp/alexandria
  #- git clone --depth=1 git://github.com/cl-babel/babel.git ~/lisp/babel

script:
  - make test-$VARIANT
  - make clean
  #- ecl -norc -eval '(format t "~A ~A~%~S~%" (lisp-implementation-type) (lisp-implementation-version) *features*)' -eval '(quit)'
  #- cl -e '(ql:quickload "graph-tgf-test")
  #         (uiop:quit (if (myam:load-and-run! "graph-tgf-test") 0 1))'
